#!/usr/bin/env python3
import sys
import yaml
import users

def help():
    print("""
git-with

Usage:
    git-with introduce <alias> <name> <email>       Introduces a new person to the script

    git-with <alias-1> <...> <alias-n>              Configures people that will be added as co-authors to your next commits

Example:
    git-with introduce bilbo "Bilbo Baggings" bilbo.baggings@shire.org

    git-with bilbo gandalf
    """)

def introduce(alias, name, email):
    users.introduce(alias, name, email)

def add(aliases):
    users.add(aliases)

def main():
    if len(sys.argv) > 1:
        match sys.argv[1]:
            case "introduce": introduce(sys.argv[2], sys.argv[3], sys.argv[4])
            case _: 
                if len(sys.argv) > 2: 
                    add(sys.argv[2:])
    else:
        help()

if __name__ == "__main__":
    main()
