#!/usr/bin/env python3
import sys
import users

def help():
    print("""
git-without

Usage:
    git-without <alias-1> <...> <alias-n>           Removes people as co-authors of your next commits

    git-without everyone                            Removes everyone as co-authores of next commits

Example:
    git-without bilbo gandalf

    git-with everyone
    """)

def everyone():
    users.reset_current_session()

def remove():
    print("Removing people from the current coding session")

def main():
    if len(sys.argv) > 1:
        match sys.argv[1]:
            case "help": help()
            case "everyone": everyone()
            case _: remove()
    else:
        help()

if __name__ == "__main__":
    main()
