#!/usr/bin/env python3
import sys
import yaml
import users

def help():
    print("""
git-with

Usage:
    git-with introduce <alias> <name> <email>       Introduces a new person to the script

    git-with <alias-1> <...> <alias-n>              Configures people that will be added as co-authors to your next commits

Example:
    git-with introduce bilbo "Bilbo Baggings" bilbo.baggings@shire.org

    git-with bilbo gandalf
    """)

def introduce():
    print("Introducing new people")

def add():
    users.read()
    print("Add people to the current coding session")

def main():
    if len(sys.argv) > 1:
        match sys.argv[1]:
            case "introduce": introduce()
            case _: add()
    else:
        help()

if __name__ == "__main__":
    main()
